### ISSUE TITLE
waarom is je js file script niet gelinkt met de html code?

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [BibekMA/the-startup-responsive-interactieve-website#10]
https://github.com/BibekMA/the-startup-responsive-interactieve-website/blob/8f4492b93f25bfa04c21404b720711a2d6be934e/index.html#L73-L80

je kan dit stukje code weghalen zodat je de javascript code apart hebt van de html code en dit bied misschien ook wel meer overzicht

**Comment by BibekMA** [comment]
Ik heb de JS nu een een aparte file gezet en goed gelinkt
