### ISSUE TITLE
geen <br> voo relementen gebruien

### ISSUE THREAD

**Issue by Jesse-L3** [BibekMA/the-startup-responsive-interactieve-website#11]
regel 90 tot 101: je gebruik br voor je buttons terwijl het eigenlijk alleen voor text bedoeld is. Ook voor dat is het het beste om helemaal niet met br te werken

```html
<p>
          Wij zijn al jaren bezig met het ontwikkelen en designen van websites
          voor onze clienten, benieuwd naar hoe wij aan de slag gaan?<br />
          Heeft u al een lopende project, dan kunt u inloggen en uw voortgang
          controleren en bijhouden <br />
        </p>
        <span>
            <button>
              <a class="bekijk-fases" href="#">Aanmelden</a>
            </button>
            <br />
            <button>
```

mogelijke oplossing is om met max width te werken of display flex en dan de flex direction bepalen

**Comment by BibekMA** [comment]
Ik heb de a tags nu in een div gezet, en die een gestijld, ook heb ik flex gebruikt en had ik de BR niet meer nodig
