### ISSUE TITLE
Website hebt geen favi icon

### ISSUE THREAD

**Issue by Jesse-L3** [BibekMA/the-startup-responsive-interactieve-website#12]
tussen de `<head>` kan je een link element plaatsen met het volgende

`<link rel="icon" type="image/x-icon" href="/images/favicon.ico">`

in de href kan je de path plaatsen van je icoon die je als website icoon wil gebruiken.

source: W3schools

**Comment by BibekMA** [comment]
ik heb een favi icon erin gezet
