### ISSUE TITLE
eind slash binnen meta tags

### ISSUE THREAD

**Issue by OniWithTheHoodie** [BibekMA/the-startup-responsive-interactieve-website#14]
https://github.com/BibekMA/the-startup-responsive-interactieve-website/blob/8f4492b93f25bfa04c21404b720711a2d6be934e/index.html#L4-L8

slashes weg halen aan het einde van de meta tags is niet nodig.

**Comment by BibekMA** [comment]
ik heb ze er allemaal uit gehaald
