### ISSUE TITLE
Opacity van je menu tekst

### ISSUE THREAD

**Issue by Ryank2004** [BibekMA/the-startup-responsive-interactieve-website#15]
```.
nav-menu {
  position: fixed;
  left: 100%;
  transition: 0.3s;
}
.nav-menu.active {
  left: 0;
  background: var(--blauw---);
  width: 100%;
  height: 13em;
  text-align: center;
  padding-top: 2em;
  color: white;
  list-style: none;
}
```

Als je op mobiel op het hamburger menu klikt komt het menu mooi in beeld. Alleen verander je niet de opacity van de tekst als je het menu weer dichtklapt. Hierdoor zie je de tekst er uit vliegen.

**Comment by BibekMA** [comment]
Ik ga de opacity verander naar 0 als je weer wegklikt
