### ISSUE TITLE
a tag in button

### ISSUE THREAD

**Issue by OniWithTheHoodie** [BibekMA/the-startup-responsive-interactieve-website#17]
https://github.com/BibekMA/the-startup-responsive-interactieve-website/blob/8f4492b93f25bfa04c21404b720711a2d6be934e/index.html#L97-L99

a tag uit de button halen. je kunt de a tag stijlen in button en het op die manier gebruiken

**Comment by BibekMA** [comment]
Ik heb de A tag gestijld als een button, en de button zelf eruit gehaald
