### ISSUE TITLE
in een span hoeft geen button of een link

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [BibekMA/the-startup-responsive-interactieve-website#8]
https://github.com/BibekMA/the-startup-responsive-interactieve-website/blob/8f4492b93f25bfa04c21404b720711a2d6be934e/index.html#L96-L104

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span zie de documentatie een span word meer gebruikt voor bijvoorbeeld 1 woord of een klein stukje tekst

**Comment by BibekMA** [comment]
Ik heb de span eruit gehaald, er de twee a links staan nu in een div
